//-----------------------------------------------------------------------------
// wx.NET - control.inc
//
// The wxControl virtual function dispatchers.
//
// Written by Jason Perkins (jason@379.com)
// (C) 2003 by 379, Inc.
// Licensed under the wxWidgets license, see LICENSE.txt for details.
//
// $Id: control.inc,v 1.9 2006/11/17 15:21:03 afb Exp $
//-----------------------------------------------------------------------------

#include "window.inc"
