all:
	-del *.cached
	#cd Controls
	#dmmake
	cd ..\Dialogs
	dmmake
#	cd ..\Display
#	dmmake
	cd ..\Dnd
	dmmake
	cd ..\EventDemo
	dmmake
	cd ..\Font
	dmmake
#	cd ..\GLCube
#	dmmake
	cd ..\Grid
	dmmake
	cd ..\Hello
	dmmake
	cd ..\HTML
	dmmake
	cd ..\HtmlHelp
	dmmake
	cd ..\HtmlListBox
	dmmake
	cd ..\Internat
	dmmake
	cd ..\Launcher
	dmmake
	cd ..\ListCtrl
	dmmake
	cd ..\ListView
	dmmake
	cd ..\Listbook
	dmmake
	cd ..\Mdi
	dmmake
	cd ..\Minimal
	dmmake
	cd ..\Notebook
	dmmake
	cd ..\Platform
	dmmake
	cd ..\Printing
	dmmake
	cd ..\SashWindow
	dmmake
#	cd ..\Sound
#	dmmake
	cd ..\Splitter
	dmmake
#	cd ..\StyledText
#	dmmake
#	cd ..\TaskBar
#	dmmake
	cd ..\TreeCtrl
	dmmake
#	cd ..\Tutorial
#	dmmake
	cd ..\Wizard
	dmmake
	cd ..\Xrc
	dmmake
#	cd ..\Aui
#	dmmake
	cd ..

clean:
	cd Controls
	dmmake clean
	cd ..\Dialogs
	dmmake clean
	cd ..\Display
	dmmake clean
	cd ..\Dnd
	dmmake clean
	cd ..\EventDemo
	dmmake clean
	cd ..\Font
	dmmake clean
	cd ..\GLCube
	dmmake clean
	cd ..\Grid
	dmmake clean
	cd ..\Hello
	dmmake clean
	cd ..\HTML
	dmmake clean
	cd ..\HtmlHelp
	dmmake clean
	cd ..\HtmlListBox
	dmmake clean
	cd ..\Internat
	dmmake clean
	cd ..\Launcher
	dmmake clean
	cd ..\ListCtrl
	dmmake clean
	cd ..\ListView
	dmmake clean
	cd ..\Listbook
	dmmake clean
	cd ..\Mdi
	dmmake clean
	cd ..\Minimal
	dmmake clean
	cd ..\Notebook
	dmmake clean
	cd ..\Platform
	dmmake clean
	cd ..\Printing
	dmmake clean
	cd ..\SashWindow
	dmmake clean
	cd ..\Sound
	dmmake clean
	cd ..\Splitter
	dmmake clean
	cd ..\StyledText
	dmmake clean
	cd ..\TaskBar
	dmmake clean
	cd ..\TreeCtrl
	dmmake clean
	cd ..\Tutorial
	dmmake clean
	cd ..\Wizard
	dmmake clean
	cd ..\Xrc
	dmmake clean
	cd ..\Aui
	dmmake clean
	cd ..

